### ISSUE TITLE
Error in Kodi 

### ISSUE THREAD

**Issue by elschmidtorado** [chamchenko/plugin.video.nbainternational#18]
Hi,

i used the ivankokan nba addon on my kodi coreelec box and it works fine. But since yesterday it is not working anymore. I get an Error from Kodi....

So i installed your addon and i get the same error. 

Is there anything that i can do to solve it???

greets

**Comment by chamchenko** [comment]
Hi @elschmidtorado,
I need a full debug log to see what's going wrong, otherwise there is no way I could know how to help you.

**Comment by elschmidtorado** [comment]
Hi,

is that the log? 

2022-03-16 19:26:58.826 T:4086427712   ERROR: Previous line repeats 46 times.
2022-03-16 19:26:58.827 T:4086427712   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2022-03-16 19:26:58.877 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:00.018 T:3877630848   ERROR: Previous line repeats 1 times.
2022-03-16 19:27:00.019 T:3877630848 WARNING: [NBA-International] Creating Main Menu
2022-03-16 19:27:00.880 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:25.689 T:3877630848   ERROR: Previous line repeats 24 times.
2022-03-16 19:27:25.690 T:3877630848   ERROR: [NBA-International.support] 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 68, in __call__
                                                return self._process_results(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 287, in _process_results
                                                listitem = self._process_item(1, next(resolved))
                                              File "/storage/.kodi/addons/plugin.video.nbainternational/resources/lib/games.py", line 563, in PLAY_GAME
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
2022-03-16 19:27:25.906 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:36.052 T:4086427712   ERROR: Previous line repeats 10 times.
2022-03-16 19:27:36.052 T:4086427712   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nbainternational/resources/lib/games/play_game/?_pickle_=80027d710128550a67616d655f737461746571024b03550667616d6549447103580a00000030303232313031303332710455046e616d657105581900000046756c6c2047616d6520486f6d65204665656420284e4f5029710655075f7469746c655f7107581900000046756c6c2047616d6520486f6d65204665656420284e4f5029550a73746172745f74696d6571088a06584f06907f015502726471098955026774710a4b015508656e645f74696d65710b8a06300889907f015502636e710c4e752e]
2022-03-16 19:27:36.914 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:43.001 T:3414160256   ERROR: Previous line repeats 5 times.
2022-03-16 19:27:43.001 T:3414160256   ERROR: [NBA-International.support] 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 68, in __call__
                                                return self._process_results(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 287, in _process_results
                                                listitem = self._process_item(1, next(resolved))
                                              File "/storage/.kodi/addons/plugin.video.nbainternational/resources/lib/games.py", line 563, in PLAY_GAME
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
2022-03-16 19:27:43.060 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:45.662 T:4086427712   ERROR: Previous line repeats 2 times.
2022-03-16 19:27:45.662 T:4086427712  NOTICE: NFS is idle. Closing the remaining connections.
2022-03-16 19:27:46.062 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:49.305 T:4086427712   ERROR: Previous line repeats 3 times.
2022-03-16 19:27:49.305 T:4086427712   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nbainternational/resources/lib/games/play_game/?_pickle_=80027d710128550a67616d655f737461746571024b03550667616d6549447103580a00000030303232313031303331710455046e616d657105581900000046756c6c2047616d6520486f6d65204665656420284d494129710655075f7469746c655f7107581900000046756c6c2047616d6520486f6d65204665656420284d494129550a73746172745f74696d6571088a0648d0ea8f7f015502726471098955026774710a4b015508656e645f74696d65710b8a06e0eb81907f015502636e710c4e752e]
2022-03-16 19:27:50.064 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:27:59.669 T:3388982144   ERROR: Previous line repeats 9 times.
2022-03-16 19:27:59.669 T:3388982144   ERROR: [NBA-International.support] 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 68, in __call__
                                                return self._process_results(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 287, in _process_results
                                                listitem = self._process_item(1, next(resolved))
                                              File "/storage/.kodi/addons/plugin.video.nbainternational/resources/lib/nba_tv.py", line 57, in NBA_TV
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
2022-03-16 19:28:00.249 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 19:28:07.473 T:4086427712   ERROR: Previous line repeats 7 times.
2022-03-16 19:28:07.473 T:4086427712   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nbainternational/resources/lib/nba_tv/nba_tv/?_pickle_=80027d710155075f7469746c655f710258060000004e4241205456732e]
2022-03-16 19:28:08.256 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file

**Comment by tent-icle** [comment]
I had the same issue. It’s resolved upstream by emilsvennesson/script.module.inputstreamhelper#495

**Comment by elschmidtorado** [comment]
Hi,

the problem cannot be solved by this

> I had the same issue. It’s resolved upstream by https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495

i tried it and checked the new line, installed it completly new, everthing i tried does not work. I always get an error from kodi.

Is there anything i can do??
