### ISSUE TITLE
401 client error for url: https://nbaapi.neulion.com/api_nba/v1/account/subscriptions

### ISSUE THREAD

**Issue by jimbobjonesbob** [chamchenko/plugin.video.nbainternational#21]
[kodi.log](https://github.com/chamchenko/plugin.video.nbainternational/files/9620943/kodi.log) with debug on

running beta 20
tried on multiple nba league pass accounts, same error
tried uninstalling addon and reinstalling.

**Comment by Judge33** [comment]
Same here, although I can see different behavior:
My ongoing renewal account works fine. I started a new subscription today with an already existing account (just without subscription) and it doesn't play. Error message in kodi.log:

ERROR <general>: [NBA-International.support] 400 Client Error:  for url: https://nbaapi.neulion.com/api_nba/v1/publishpoint
                                                   Traceback (most recent call last):
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 68, in __call__
                                                       return self._process_results(results)
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 287, in _process_results
                                                       listitem = self._process_item(1, next(resolved))
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.nbainternational\resources\lib\games.py", line 508, in PLAY_GAME
                                                       Response = urlquick.post(
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 510, in post
                                                       return request('post', url, data=data, json=json, **kwargs)
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "C:\Users\Judge\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error:  for url: https://nbaapi.neulion.com/api_nba/v1/publishpoint

Seems to be a different URL though

Neulion changed login to what they call NBA ID. Probably new identification method for new subscriptions?

**Comment by Judge33** [comment]
No, a difference in new vs. old subscription or changed sign on doesn't seem to be it. Both accounts work on KODI 18 after I have gotten my subscription confirmation (it was late).
But there seems to be a difference from KODI 18 to 19. In 18 I can log in and watch on both accounts, in KODI 19 I can on neither. It shows the "400 Client Error" in the log. But I also had a type error "path" "setpath" must be src or something like that in the log once. However, I could not replicate that error and the log was overwritten.

**Comment by jimbobjonesbob** [comment]
I had a version of Kodi on PC that didn't work, but then , it got a InputStream Adaptive addon update, and then it worked. Addon version 19.0.7

I mainly use Coreelec which is 19.5 rc2 and it has always worked, but doesn't now. It has InputStream Adaptive version 19.0.7.1.

I really want the Coreelec to work (like it always has).

**Comment by Judge33** [comment]
OK, directly after installation there was the "path" error again, see here:

ERROR: [NBA-International.support] argument "path" for method "setPath" must be unicode or str
                                            Traceback (most recent call last):
                                              File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 68, in __call__
                                                return self._process_results(results)
                                              File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 287, in _process_results
                                                listitem = self._process_item(1, next(resolved))
                                              File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 247, in _process_item
                                                listitem.setPath(url)
                                            TypeError: argument "path" for method "setPath" must be unicode or str

Any idea?

**Comment by Judge33** [comment]
I got it up and running. Login and playback are working now with no difference between old subscription and new one.
I don't know when and why, but the addon created the following files in the local userdata/addon_data/plugin.video.nbainternational folder:
.accountinfo.profileinfo
.accountinfo.token
.urlquick.slite3
Without these, I get error messages like posted above.
I run serveral clients and you have to copy these files to the local folder although I have a pathredirection of the addon_data folder to a network location. Interestingly the setting.xml is being saved on the network location, the three files above locally. Beats me, but it works now. I have no clue, when the addon created those files.

Hope it will last as I really like the the addon.

**Comment by jimbobjonesbob** [comment]
> accountinfo.profileinfo .accountinfo.token .urlquick.slite3 Without these, I get error messages like posted above. 

Thanks for that. I had those files in my directory, but when I overwrote them from files in my other kodi installation it got it going.

edit: although it appears I did connect to my old account first - before changing credentials to my newly created account.
If I try and use my newer account's credentials first, I get Error 401

**Comment by Judge33** [comment]
With further testing today, I was able to narrow down the problem. It seem that indeed there is a change in authentication. This is what I could see:

Opening the addon creates the ".accountinfo.profilinfo" file and an ".urlquick.slite3" file. The url file already contains email and passwort from the settings.xml.
After you open a video stream from the addon (one that is not for free), ".accountinfo.token" is created and the urlquick file contains authentification info on your account via https://nbaapi.neulion.com/api_nba/v1/account/subscriptions

Now: when I try the credentials of last season's pass it works fine
But I opened a new account 2 days ago and that one does not return the permission/correct subscription information and accordingly is unable to find streaming urls which results in the 400 error.

What is more, that is the same in the old NBA League Pass Addon, so I guess the authentication method of the newer accounts is different and it is probable that older subscriptions will be changed in the renewal process.

I hope this information helps to adjust the addon. KODI is the most comfortable way to watch the games and my absolute favorite. Unfortunately I am not able to code and I have absolutely no clue on how to find out what changes there are at neulion login.

**Comment by Judge33** [comment]
Looks like my old "renew subscription" account got updated today. As expected now neither that nor the new account is able to login in cleanly in NBA International or NBA League Pass Addon. No games are playing. I receive 400 Client error.

**Comment by RHStonks** [comment]
> Looks like my old "renew subscription" account got updated today. As expected now neither that nor the new account is able to login in cleanly in NBA International or NBA League Pass Addon. No games are playing. I receive 400 Client error.

@Judge33 I'm also getting that PUBLISHPOINT error as well. Is it working for you today? 

@chamchenko any updates on what's causing this problem and if possible to update a newer version for the addon?

**Comment by jimbobjonesbob** [comment]
Not working for me. Error 400.

**Comment by RHStonks** [comment]
> Not working for me. Error 400.

I got that error code as well. Hopefully @chamchenko updates the addon soon. Last update was June and they probably updated the accounttoken api so that's why it's not working.

**Comment by Judge33** [comment]
Nope, all errors here.

**Comment by anjaklama** [comment]
NBA League pass changed providers from Neulion to Microsoft. They are in the process of changing their entire setup, so things has changed A LOT and will continue to change. it is not going to be easy to update the plugin.

**Comment by nre-ableton** [comment]
Ah, that's such a bummer. I'll take a look at this add-on when I have a bit of spare time and see if I can't help find a solution.

**Comment by scottydulton** [comment]
@nre-ableton thanks, much appreciated

**Comment by chamchenko** [comment]
Hi, sorry I've been really busy lately. I will try to have a look at this as soon as I can, maybe this weekend.

**Comment by scottydulton** [comment]
@chamchenko thanks buddy

**Comment by Judge33** [comment]
@everyone: so happy to see the addon alive and well!

**Comment by chamchenko** [comment]
Sadly I was about to start working on it and I found out that my subscription has expired. I won't be able to renew it before the beginning of next month.

**Comment by anjaklama** [comment]
@chamchenko you can still watch the pre-season games.

**Comment by scottydulton** [comment]
@chamchenko would you like to borrow my account?

**Comment by chamchenko** [comment]
> @chamchenko would you like to borrow my account?

I've sent you a private message on kodi forum.

**Comment by scottydulton** [comment]
> > @chamchenko would you like to borrow my account?
> 
> I've sent you a private message on kodi forum.

ive emailed you mate :) hope you can sort it

**Comment by anjaklama** [comment]
Keep in mind the NBA app is probably going to switch to adobe primetime DRM soon...

**Comment by nre-ableton** [comment]
Unfortunately, I don't think I'll have time to look at this in the upcoming week.

**Comment by RHStonks** [comment]
Any updates?

**Comment by tent-icle** [comment]
I started looking into this last weekend. The use of Adobe Primetime (streams.adobeprimetime.com, etc) seems a pretty difficult obstacle to overcome. As best I can tell, there hasn't been a linux client since this was decoupled from Flash in 2016, no matter an ARM client, no matter a plugin for Kodi. If anyone has examples to the contrary, please post them here!

Meanwhile, Microsoft have also handled the transition very poorly. My usual workaround when this plugin broke was to use the official PS4 app. They appear to have silently dropped support for this  - it was still listed as a supported paltform on the day the season began but now is not. 

Perhaps the best option will be for as many of us as possible to get the NBA to refund their subsubscription unless and until this mess is sorted out...

**Comment by jimbobjonesbob** [comment]
I am using the FireTV NBA app which works well. The controls aren't as good
as Kodi though

**Comment by nre-ableton** [comment]
> I started looking into this last weekend. The use of Adobe Primetime (streams.adobeprimetime.com, etc) seems a pretty difficult obstacle to overcome. As best I can tell, there hasn't been a linux client since this was decoupled from Flash in 2016, no matter an ARM client, no matter a plugin for Kodi. If anyone has examples to the contrary, please post them here!

Ugh, I'm not sure why they would use such a weird technology, but I agree with you that this will probably be a challenge to support. 

> Meanwhile, Microsoft have also handled the transition very poorly. My usual workaround when this plugin broke was to use the official PS4 app. They appear to have silently dropped support for this - it was still listed as a supported paltform on the day the season began but now is not.

Understatement of the year. Our poor unofficial Kodi plugin is broken, but the official NBA apps and the NBA website are a complete disaster. I reported a ton of bugs to NBA support this weekend, and at least they are attentive (even if the support staff just follow some pre-written script and don't actually read the emails :sweat_smile:).

> Perhaps the best option will be for as many of us as possible to get the NBA to refund their subscription unless and until this mess is sorted out...

As much as I love the Kodi plugin, I don't think I'll actually do that, since I can deal with the official apps until we find a workaround. But if you feel strongly about it, then go ahead. However, I doubt that NBA support will pay much attention to your reasons for cancelling the subscription.

**Comment by Judge33** [comment]
Is the addon still alive? 

I very much hope there is someone out there with the knowledge and the time to fix that thing. In my despair I actually took a look at the code myself only to find out that I have no clue. No surprise as I have never successfully coded anything before.

And I really miss watching NBA on Kodi.
Using the browser OR the app is so crappy that it physically hurts!
NBA League Pass is a train wreck at the moment, but a working addon would at least ease the pain of unpricise edditing (ugh), spoiled results (aaahhhh) and not being able to watch the Clippers (ClipperVision) with comfy forwarding, rewinding, skipping and highlight watching (a pain in browser version).

I am sorry to say that I am of no use in that matter. If I can contribute in any form, like testing and reporting bugs maybe, please write a message.

PLEASE SOMEBODY HELP!

**Comment by RHStonks** [comment]
> Is the addon still alive? 
> 
> 
> 
> I very much hope there is someone out there with the knowledge and the time to fix that thing. In my despair I actually took a look at the code myself only to find out that I have no clue. No surprise as I have never successfully coded anything before.
> 
> 
> 
> And I really miss watching NBA on Kodi.
> 
> Using the browser OR the app is so crappy that it physically hurts!
> 
> NBA League Pass is a train wreck at the moment, but a working addon would at least ease the pain of unpricise edditing (ugh), spoiled results (aaahhhh) and not being able to watch the Clippers (ClipperVision) with comfy forwarding, rewinding, skipping and highlight watching (a pain in browser version).
> 
> 
> 
> I am sorry to say that I am of no use in that matter. If I can contribute in any form, like testing and reporting bugs maybe, please write a message.
> 
> 
> 
> PLEASE SOMEBODY HELP!
> 
> 
> 
> 

I miss the Kodi addon. Recent NBA app versions on my tablet have made it completely useless since it requires my location even though I have location enabled it still won't play the video. Right now I'm using a previous app version which fixes the issue but I have no idea how long this will last until it forces me to update. 

Has anyone looked at the NBA kodi addon a bit more to see if it can be fixed anytime soon?
