### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by nickomaru** [chamchenko/plugin.video.nbainternational#7]
hello
i have message 
<general>: [NBA-International.support] Incorrect padding

>Traceback (most recent call last):
                                                     File "C:\Users\N.....\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\N......\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 68, in __call__
                                                       return self._process_results(results)
                                                     File "C:\Users\N......\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 287, in _process_results
                                                       listitem = self._process_item(1, next(resolved))
                                                     File "C:\Users\N......\AppData\Roaming\Kodi\addons\plugin.video.nbainternational\resources\lib\games.py", line 478, in PLAY_GAME
                                                       headers = get_headers()
                                                     File "C:\Users\N......\AppData\Roaming\Kodi\addons\plugin.video.nbainternational\resources\lib\auth.py", line 222, in get_headers
                                                       access_token = get_token()
                                                     File "C:\Users\N.....\AppData\Roaming\Kodi\addons\plugin.video.nbainternational\resources\lib\auth.py", line 118, in get_token
                                                       exp = json.loads(b64decode(access_token.split('.')[1]))['exp']
                                                     File "C:\Program Files\Kodi\system\python\Lib\base64.py", line 87, in b64decode
                                                       return binascii.a2b_base64(s)
                                                   binascii.Error: Incorrect padding

> 

once works 10 times error

**Comment by nickomaru** [comment]
very difficult?

https://i.imgur.com/VyhUUpd.png

**Comment by chamchenko** [comment]
Hi, I will need the full debug log, and some detail on how often it happens (what games..)
I will look into it as soon as I have time

**Comment by nickomaru** [comment]
[kodi.zip](https://github.com/chamchenko/plugin.video.nbainternational/files/7305747/kodi.zip)
это сообщение возникает на любой игре
один раз в день нормально покажет,потом уже с этой ошибкой
this message appears in any game
it will show normally once a day, then with this error

log created!

**Comment by chamchenko** [comment]
Can you test with this [test.zip](http://github.com/chamchenko/plugin.video.nbainternational/archive/refs/heads/test.zip)??

**Comment by nickomaru** [comment]
hello!
very good!
no errors!
I ran several games in a row - everything works!

**Comment by jimbobjonesbob** [comment]
was having the incorrect padding issue also (always after stopping a game then trying to restart it)
so far I can say that beta 19 fixed it

**Comment by chamchenko** [comment]
Hi @jimbobjonesbob, can you confirm that you have a one team subscription? I think this issue may appear for user who do not have a full subscription. the solution in the test zip is supposed to be a temporary fix until I get more info on this. Sadly lately I don't have much free time to make further looking into this.

**Comment by jimbobjonesbob** [comment]
> Hi @jimbobjonesbob, can you confirm that you have a one team subscription? I think this issue may appear for user who do not have a full subscription. the solution in the test zip is supposed to be a temporary fix until I get more info on this. Sadly lately I don't have much free time to make further looking into this.

I have a full league pass subscription

**Comment by chamchenko** [comment]
This should be fixed in the latest version so I'm closing this.
